version: "3"

services:
  short-creator:
    build:
      context: .
      dockerfile: main.Dockerfile
    env_file:
      - .env
    environment:
      - DEV=false
      - OPENAI_API_KEY=
    ports:
      - "3123:3123"
    entrypoint: ["node", "dist/index.js"]
